#ifndef VERSION_H
#define VERSION_H

#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 2
#define APP_VERSION_PATCH 8
#define APP_VERSION_BUILD 0

#define APP_VERSION_STRING "1.2.8"
#define APP_VERSION_TAG "v1.2.8"

#endif // VERSION_H