#ifndef VERSION_H
#define VERSION_H

#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 4
#define APP_VERSION_PATCH 0
#define APP_VERSION_BUILD 0

#define APP_VERSION_STRING "1.4.0"
#define APP_VERSION_TAG "v1.4.0"

#endif // VERSION_H